name: diff
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - transformers>=4.25.1
  - pip:
      - accelerate
      - torchvision
      - ftfy
      - tensorboard
      - modelcards
      - -e git+https://github.com/huggingface/diffusers.git#egg=diffusers
